apiVersion: apps/v1
kind: Deployment
metadata:
  name: markwcodes
  labels:
    name: markwcodes
spec:
  selector:
    matchLabels:
      app: markwcodes
  replicas: 1
  template:
    metadata:
      labels:
        app: markwcodes
    spec:
      volumes:
      - name: shared-volume
        emptyDir: { }
      - name: nginx-server-config-volume
        configMap:
          name: nginx-server-config
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-server-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: shared-volume
          mountPath: /var/www/markwcodes
      - name: php-fpm
        image: ghcr.io/markwcodes/personal-website:1.0.1
        ports:
        - containerPort: 9000
        # envFrom:
        # - configMapRef:
        #     name: 
        volumeMounts:
        - name: shared-volume
          mountPath: /var/www/markwcodes
        lifecycle:
          postStart:
            exec:
              command: 
                - "/bin/sh" 
                - "-c"
                - |
                  mv /var/www/html/* /var/www/markwcodes/ && \
                  chown -R www-data:www-data /var/www/markwcodes/storage/ && \
                  chmod -R 775 /var/www/markwcodes/storage/ && \
                  chown -R www-data:www-data /var/www/markwcodes/bootstrap/cache && \
                  chmod -R 775 /var/www/markwcodes/bootstrap/cache
