apiVersion: apps/v1
kind: Deployment
metadata:
  name: markwcodes
  labels:
    name: markwcodes
spec:
  selector:
    matchLabels:
      app: markwcodes
  replicas: 1
  template:
    metadata:
      labels:
          app: markwcodes
    spec:
      containers:
      - name: php-fpm
        image: php:8.2-fpm-alpine # todo: replace with my app image
        ports:
        - containerPort: 9000
        # envFrom:
        # - configMapRef:
        #     name: 
        volumeMounts:
        - name: shared-volume
          mountPath: /var/www
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-server-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: shared-volume
          mountPath: /var/www
      volumes:
      - name: shared-volume
        emptyDir: { }
      - name: nginx-server-config-volume
        configMap:
          name: nginx-server-config
