---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- load-balancer.yaml

configMapGenerator:
  - name: nginx-server-config
    files:
      - nginx/default.conf