applications:
  - name: markwcodes
    project: default
    source:
      repoURL: https://github.com/markwcodes/personal-website-infra.git
      targetRevision: HEAD
      path: gitops-config/manifests/markwcodes-app
    destination:
      server: https://kubernetes.default.svc
      namespace: staging
    syncPolicy:
      automated:
        prune: true
        selfHeal: false
      syncOptions:
        - CreateNamespace=false
    info:
      - name: url
        value: https://staging.wilson.codes