name: Build and Publish App
on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "App version using semantic versioning without the 'v' (1.2.3)"
        required: false
        default: 'latest'
env:
  REGISTRY: ghcr.io
  APP_REPO: markwcodes/personal-website
  BUILD_REF: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout app repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.APP_REPO }}
        ref: ${{ env.BUILD_REF }}
    - name: Set outputs from checkout
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Checkout build tools
      uses: actions/checkout@v4
      with:
        path: infra
        sparse-checkout: |
          docker/markwcodes-app
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: infra/docker/markwcodes-app/Dockerfile
        context: .
        push: true
        build-args: |
          APP_VERSION=${{ env.INPUT_APP_VERSION }}
          COMMIT_HASH=${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.APP_REPO }}:latest
          ${{ env.REGISTRY }}/${{ env.APP_REPO }}:${{ github.event.inputs.app_version }}
          ${{ env.REGISTRY }}/${{ env.APP_REPO }}:${{ steps.vars.outputs.sha_short }}
