name: Create Terraform plan on Pull Request

on:
  pull_request:
    branches:
      - staging
      - production

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan from terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Create tfvars file'
        run: |
          echo '${{ vars.tfvars }}' > terraform/terraform.tfvars

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          workspace: ${{ github.base_ref }}
          backend_config: |
            access_key=${{ secrets.spaces_access_token }}
            secret_key=${{ secrets.spaces_secret_key }}
            bucket=${{ secrets.tf_state_bucket }}
          variables: |
            do_token="${{ secrets.DO_TOKEN }}"
            app_key="${{ secrets.app_key }}"
          var_file: |
            terraform/terraform.tfvars
