name: Create terraform plan on Pull Request

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          workspace: ${{ github.base_ref }}
          backend_config: access_key=${{ secrets.TF_VAR_spaces_access_token }},secret_key=${{ secrets.TF_VAR_spaces_secret_key }},bucket=${{ secrets.TF_VAR_tf_state_bucket }}
