name: Apply Terraform plan from Pull Request

on:
  pull_request_target:
    types:
      - closed
    branches:
      - production
      - staging

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Create tfvars file'
        run: |
          echo '${{ vars.tfvars }}' > terraform/terraform.tfvars

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          workspace: ${{ github.base_ref }}
          backend_config: |
            access_key=${{ secrets.spaces_access_token }}
            secret_key=${{ secrets.spaces_secret_key }}
            bucket=${{ secrets.tf_state_bucket }}
          variables: |
            do_token="${{ secrets.DO_TOKEN }}"
          var_file: |
            terraform/terraform.tfvars
